# Custom
spacing = 1
padding = 2

hide_ascii = true
prefer_small_ascii = true

separator = ""
key_color = "#ffffff"
separator_color = "#d81831"

[palette]
type = "Dark"
glyph = "  "
visible = false

[box]
title = " System Info "
border = "rounded"
visible = true

[box.inner_margin]
x = 0
y = 0

[keys]
distro = " "
wm = "  "
shell = "  "
packages = "󰏖  "
terminal = "  "
uptime = "󰔛  "
